SET FOREIGN_KEY_CHECKS=0;
INSERT INTO STUDENTE VALUES("SMITH",17,1,"CS");
INSERT INTO STUDENTE VALUES("BROWN",8,2,"CS");
INSERT INTO INSEGNAMENTO VALUES ("INTRO INFO","1310",4,"CS");
INSERT INTO INSEGNAMENTO VALUES ("STRUTT DATI","3320",4,"CS");
INSERT INTO INSEGNAMENTO VALUES ("MAT DISCRETA","2410",3,"MATH");
INSERT INTO INSEGNAMENTO VALUES ("BASI DATI","3380",3,"CS");







SET FOREIGN_KEY_CHECKS=1;