SELECT NUMERO_COPIE
FROM COPIE_LIBRO
WHERE ID_LIBRO="LTP1" AND ID_BIBLIOTECA="P1";

SELECT SUM(NUMERO_COPIE) AS COPIE_TOTALI
FROM COPIE_LIBRO
WHERE ID_LIBRO="LTP1";

SELECT NOME_CLIENTE
FROM UTENTE	
WHERE NOT EXISTS (SELECT NOME_CLIENTE FROM PRESTITI WHERE UTENTE.N_CARTA=PRESTITI.N_CARTA);

SELECT LIBRO.TITOLO,UTENTE.NOME_CLIENTE,UTENTE.INDIRIZZO_CLIENTE
FROM LIBRO,UTENTE,PRESTITI
WHERE PRESTITI.ID_BIBLIOTECA="P1" AND PRESTITI.DATA_FINE="2019-01-28"
AND LIBRO.ID_LIBRO=PRESTITI.ID_LIBRO AND UTENTE.N_CARTA=PRESTITI.N_CARTA;

SELECT SUCCURSALE.NOME_SEZIONE, LIBRO.TITOLO,COUNT(PRESTITI.ID_LIBRO) AS PRESTITI
FROM LIBRO,PRESTITI,SUCCURSALE
WHERE LIBRO.ID_LIBRO=PRESTITI.ID_LIBRO AND SUCCURSALE.ID_BIBLIOTECA=PRESTITI.ID_BIBLIOTECA
GROUP BY SUCCURSALE.NOME_SEZIONE, LIBRO.TITOLO;

SELECT UTENTE.NOME_CLIENTE,UTENTE.INDIRIZZO_CLIENTE,COUNT(PRESTITI.ID_LIBRO) AS PRESTITI
FROM UTENTE,PRESTITI
WHERE UTENTE.N_CARTA=PRESTITI.N_CARTA
GROUP BY UTENTE.NOME_CLIENTE,UTENTE.INDIRIZZO_CLIENTE
HAVING COUNT(PRESTITI.ID_LIBRO)>2;

SELECT LIBRO.TITOLO,COPIE_LIBRO.NUMERO_COPIE
FROM LIBRO,COPIE_LIBRO,AUTORI,SUCCURSALE
WHERE LIBRO.ID_LIBRO=COPIE_LIBRO.ID_LIBRO AND SUCCURSALE.ID_BIBLIOTECA=COPIE_LIBRO.ID_BIBLIOTECA 
AND AUTORI.ID_LIBRO=COPIE_LIBRO.ID_LIBRO
AND AUTORI.NOME_AUTORE="STEPHEN KING" AND SUCCURSALE.NOME_SEZIONE="FERRARA CENTRO";

